name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: /var/deploy/scripts/deploy-docs.xva-lang.org.sh
